title: "AI NOOB NOOK"
description: "<p style='text-align: center; color: white; font-size: 20px;'>A beginner's guide to Artificial Intelligence.<br>Let's build your foundation in the next 60 days.</p>"
theme: jekyll-theme-time-machine
google_analytics: G-1G48EMPR8Q
baseurl: "/AI-noob-nook.github.io"

navigation:
  - name: "Home"
    url: "{{ site.baseurl }}/"
  - name: "Day 1: Introduction to Python"
    url: "{{ site.baseurl }}/day1/"
  - name: "Day 2: Types and Variables - Master the Building Blocks of Python!"
    url: "{{ site.baseurl }}/day2/"
  - name: "Day 3: Control Flow – Making Decisions in Python"
    url: "{{ site.baseurl }}/day3/"
  - name: "Day 4: Functions – Modularize Your Code with Python"
    url: "{{ site.baseurl }}/day4/"
  - name: "Lambda Function"
    url: "{{ site.baseurl }}/LambdaFunction/"
  - name: "Day 5: Exploring Data Structures in Python"
    url: "{{ site.baseurl }}/day5/"
