title: "AI NOOB NOOK"
description: "<p style='text-align: center; color: white; font-size: 20px;'>A beginner's guide to Artificial Intelligence.<br>Let's build your foundation in the next 60 days.</p>"
theme: jekyll-theme-time-machine
google_analytics: G-1G48EMPR8Q
baseurl: "/AI-noob-nook.github.io"

navigation:
  - name: "Home"
    url: "{{ site.baseurl }}/"
  - name: "Day 1: Introduction to Python"
    url: "{{ site.baseurl }}/day1/"
  - name: "Day 2: Types and Variables - Master the Building Blocks of Python!"
    url: "{{ site.baseurl }}/day2/"
  - name: "Day 3: Control Flow – Making Decisions in Python"
    url: "{{ site.baseurl }}/day3/"
  - name: "Day 4: Functions – Modularize Your Code with Python"
    url: "{{ site.baseurl }}/day4/"
  - name: "Lambda Function"
    url: "{{ site.baseurl }}/LambdaFunction/"
  - name: "Day 5: Exploring Data Structures in Python"
    url: "{{ site.baseurl }}/day5/"
  - name: "Day 6: File Handling in Python – Manage and Process Data Efficiently"
    url: "{{ site.baseurl }}/day6/"
  - name: "Day 7: Error and Exception Handling in Python – Build Resilient Code"
    url: "{{ site.baseurl }}/day7/"
  - name: "Day 8: Object-Oriented Programming (OOP) in Python – Organizing Code for Better Reusability and Structure"
    url: "{{ site.baseurl }}/day8/" 
  - name: "Day 9: Modules and Packages in Python – Organizing Your Code for Better Maintainability"
    url: "{{ site.baseurl }}/day9/"
  - name: "Day 10: Python Libraries and Frameworks – Boost Your Productivity"
    url: "{{ site.baseurl }}/day10/"
  - name: "Day 11: Python for Data Science – Let’s Analyze and Visualize Data!"
    url: "{{ site.baseurl }}/day11/"
  - name: "Day 12: NumPy Basics – Powerful Numerical Computing"
    url: "{{ site.baseurl }}/day12/"
