title: "AI NOOB NOOK"
description: "A beginner's guide to Artificial Intelligence.  Let's build your foundation in the next 60 days"
theme: jekyll-theme-leap-day

navigation:
  - name: "Home"
    url: "/"
  - name: "Day 1: Introduction to Python"
    url: "/day1/"
  - name: "Day 2:Types and Variables in Python: Strings, Integers, Floats, and Booleans"
    url: "/day2/"
