title: "AI NOOB NOOK"
description: "A beginner's guide to Artificial Intelligence.  Let's build your foundation in the next 60 days"
baseurl: ""
url: ""
theme: jekyll-theme-leap-day

navigation:
    - Home: index.md
    - Day 1: day1.md
