title: "AI NOOB NOOK"
description: "<p style='text-align: center; color: white; font-size: 20px;'>A beginner's guide to Artificial Intelligence.<br>Let's build your foundation in the next 60 days.</p>"
theme: jekyll-theme-time-machine
google_analytics: G-1G48EMPR8Q
baseurl: "/AI-noob-nook.github.io"

navigation:
  - name: "Home"
    url: "{{ site.baseurl }}/"
  - name: "Day 1: Introduction to Python"
    url: "{{ site.baseurl }}/day1/"
  - name: "Day 2:Types and Variables in Python: Strings, Integers, Floats, and Booleans"
    url: "{{ site.baseurl }}/day2/"
